general:
  environment: development

web:
  development:
    debug: false
    cookie_secret: "El Psy Congroo"
    xsrf_cookies: false
    port: 8888
    max_body_size: 536870912000000
    cache_directory: /tmp

database:
  development:
    drivername: sqlite
    database: database.db
